"""Which photo each product gets. RULES map a product name (regex) to a subject key;
SUBJECTS give the Wikimedia Commons search for that subject. Products matching no rule keep the text tile."""

SUBJECTS = {
 # vegetables
 'arrowroot':'taro corm Colocasia esculenta', 'aubergine':'aubergine eggplant', 'avocado':'Hass avocado',
 'beetroot':'beetroot bunch', 'kale_curly':'curly kale', 'kale_tuscan':'lacinato kale cavolo nero',
 'broccoli':'broccoli head', 'brussels':'Brussels sprouts', 'butternut':'butternut squash',
 'cabbage_green':'green cabbage', 'cabbage_red':'red cabbage', 'cabbage_savoy':'savoy cabbage',
 'carrots':'carrots', 'cauli_green':'green cauliflower', 'cauli_white':'cauliflower head',
 'celery':'celery stalks', 'chayote':'chayote', 'chilli_mixed':'chili peppers mixed', 'scotch_bonnet':'scotch bonnet pepper',
 'courgette':'zucchini courgette', 'cucumber':'cucumber', 'green_beans':'green beans', 'kohlrabi':'kohlrabi',
 'leeks':'leeks', 'lettuce_cos':'cos romaine lettuce', 'endive':'curly endive frisee', 'iceberg':'iceberg lettuce',
 'lollo_biondo':'lollo biondo lettuce', 'lettuce_green':'green leaf lettuce', 'lettuce_red':'red leaf lettuce lollo rosso',
 'salad_pack':'mixed salad leaves', 'maize_green':'green maize corn cob husk', 'mangetout':'snow peas mangetout',
 'mushroom_button':'button mushrooms', 'portobello':'portobello mushroom', 'okra':'okra',
 'onion_red':'red onions', 'onion_white':'white onions', 'peas':'green peas', 'pepper_green':'green bell pepper',
 'pepper_red':'red bell pepper', 'pepper_yellow':'yellow bell pepper', 'potato':'potatoes', 'potato_new':'new potatoes',
 'potato_red':'red potatoes', 'sweet_potato':'sweet potato', 'pumpkin':'pumpkin', 'radish':'radishes bunch',
 'rhubarb':'rhubarb stalks', 'spinach':'spinach leaves', 'pak_choi':'pak choi bok choy', 'baby_spinach':'baby spinach',
 'spring_onion':'spring onions scallions', 'sugar_snap':'sugar snap peas', 'sukuma':'collard greens', 'sweet_corn':'sweet corn cob',
 'tomato_cherry':'cherry tomatoes', 'tomato_round':'tomatoes', 'tomato_italian':'roma plum tomatoes',
 # fruit
 'apple_green':'green apple Granny Smith', 'apple_red':'red apple', 'plantain':'plantain bananas', 'bananas':'bananas bunch',
 'matoke':'green bananas matoke', 'blueberries':'blueberries', 'coconut':'coconut', 'grapefruit':'grapefruit',
 'grapes':'grapes', 'kiwi':'kiwifruit', 'lemons':'lemons', 'limes':'limes', 'madafu':'green tender coconut',
 'mango':'mango fruit', 'melon_sweet':'cantaloupe melon', 'melon_thorn':'kiwano horned melon', 'watermelon':'watermelon',
 'oranges':'oranges', 'pixie':'mandarin satsuma', 'passion_black':'purple passion fruit', 'passion_yellow':'yellow passion fruit',
 'pawpaw':'papaya', 'pawpaw_mountain':'mountain papaya babaco', 'pears':'pears', 'pineapple':'pineapple',
 'pomegranate':'pomegranate', 'raspberries':'raspberries', 'strawberries':'strawberries', 'strawberries_frozen':'frozen strawberries',
 'tangerines':'tangerines', 'tree_tomato':'tamarillo tree tomato',
 # herbs
 'basil':'basil', 'chives_flat':'garlic chives', 'chives':'chives', 'coriander':'coriander cilantro', 'edible_flowers':'edible flowers',
 'fennel':'fennel bulb', 'garlic':'garlic bulbs', 'ginger':'ginger root', 'lemon_grass':'lemongrass', 'marjoram':'marjoram',
 'mint':'mint leaves', 'apple_mint':'apple mint', 'oregano':'oregano', 'parsley_curly':'curly parsley', 'parsley_flat':'flat leaf parsley',
 'rocket':'rocket arugula', 'rosemary':'rosemary', 'sage':'sage herb', 'tarragon':'tarragon', 'thyme':'thyme', 'turmeric':'fresh turmeric root',
 'watercress':'watercress',
 # live plants
 'artichoke':'globe artichoke', 'gooseberry':'gooseberries', 'herb_box':'potted herbs', 'lemon_verbena':'lemon verbena',
 'sorrel':'sorrel', 'strawberry_plant':'strawberry plant', 'strawberry_runner':'strawberry plant runner',
 # dairy
 'bocconcini':'bocconcini', 'brie':'brie cheese', 'camembert':'camembert', 'cheddar':'cheddar cheese', 'cottage_cheese':'cottage cheese',
 'cream_cheese':'cream cheese', 'baba_ganoush':'baba ganoush', 'feta_dip':'whipped feta dip', 'eggs':'chicken eggs',
 'feta':'feta cheese', 'gouda':'gouda cheese', 'greek_yogurt':'greek yogurt', 'halloumi':'halloumi', 'hummus':'hummus',
 'mascarpone':'mascarpone', 'milk':'glass of milk', 'cream':'cream pouring', 'mozzarella':'mozzarella', 'paneer':'paneer',
 'ricotta':'ricotta', 'sour_cream':'sour cream', 'string_cheese':'string cheese', 'blue_cheese':'blue cheese',
 'ice_vanilla':'vanilla ice cream', 'ice_chocolate':'chocolate ice cream', 'ice_caramel':'caramel ice cream', 'ice_cookies':'cookies and cream ice cream',
 # meat & fish
 'boerwors':'boerewors', 'striploin':'striploin steak', 'chicken_whole':'whole raw chicken', 'chicken_breast':'chicken breast raw',
 'chicken_liver':'chicken liver', 'chicken_thigh':'chicken thighs raw', 'droewors':'droewors', 'duck_whole':'whole duck raw',
 'duck_breast':'duck breast', 'duck_legs':'duck legs', 'snapper':'snapper fillet', 'ham':'glazed ham', 'minced_beef':'minced beef',
 'pork_ribs':'pork spare ribs raw', 'pork_chops':'pork chops', 'prawns':'peeled prawns', 'pork_sausages':'pork sausages',
 'salmon_burger':'salmon burger', 'salmon_portion':'salmon fillet raw', 'smoked_salmon':'smoked salmon', 'squid':'squid cleaned', 'bacon':'streaky bacon',
 # drinks / pantry
 'apple_juice':'apple juice glass', 'beetroot_juice':'beetroot juice', 'madafu_bottle':'coconut water', 'mango_juice':'mango juice',
 'orange_juice':'orange juice glass', 'passion_juice':'passion fruit juice', 'pineapple_juice':'pineapple juice', 'tree_tomato_juice':'tamarillo juice',
 'kombucha':'kombucha bottle', 'water_still':'bottled water', 'water_sparkling':'sparkling water bottle', 'water_big':'water cooler bottle 20 litre',
 'chutney':'chutney jar', 'harissa':'harissa', 'honey':'honey jar', 'jam':'jam jar', 'marmalade':'orange marmalade jar', 'tea':'loose tea leaves',
 'bouquet':'flower bouquet',
}

RULES = [
 (r'^Arrow Root','arrowroot'),(r'^Aubergine','aubergine'),(r'^Avocado','avocado'),(r'^Beetroot$','beetroot'),
 (r'Curly Kale','kale_curly'),(r'Tuscan Kale','kale_tuscan'),(r'^Broccoli','broccoli'),(r'^Brussels','brussels'),
 (r'^Butter Nut','butternut'),(r'^Cabbage \(Green','cabbage_green'),(r'^Cabbage \(Red','cabbage_red'),(r'^Cabbage \(Savoy','cabbage_savoy'),
 (r'^Carrots','carrots'),(r'^Cauliflower \(Green','cauli_green'),(r'^Cauliflower \(White','cauli_white'),(r'^Celery','celery'),
 (r'^Chayote','chayote'),(r'^Chillies \(Mixed','chilli_mixed'),(r'^Chillies \(Scotch','scotch_bonnet'),(r'^Courgette','courgette'),
 (r'^Cucumber','cucumber'),(r'^Green Beans','green_beans'),(r'^Kohl','kohlrabi'),(r'^Leeks','leeks'),
 (r'^Lettuce \(Cos','lettuce_cos'),(r'^Lettuce \(Endive','endive'),(r'^Lettuce \(Iceberg','iceberg'),(r'^Lettuce \(Lollo','lollo_biondo'),
 (r'^Lettuce \(Ronali','lettuce_green'),(r'^Lettuce \(Rubili','lettuce_red'),(r'^Lettuce \(Salad','salad_pack'),
 (r'^Maize','maize_green'),(r'^Mangetout','mangetout'),(r'^Mushroom \(Button','mushroom_button'),(r'^Mushroom \(Portobello','portobello'),
 (r'^Okra','okra'),(r'^Onions \(Red','onion_red'),(r'^Onions \(White','onion_white'),(r'^Peas','peas'),
 (r'^Pepper \(Green','pepper_green'),(r'^Pepper \(Red','pepper_red'),(r'^Pepper \(Yellow','pepper_yellow'),
 (r'^Potatoes Sweet','sweet_potato'),(r'^Potatoes \(New','potato_new'),(r'^Potatoes \(Red','potato_red'),(r'^Potatoes$','potato'),
 (r'^Pumpkin','pumpkin'),(r'^Radish','radish'),(r'^Rhubarb \(Live','rhubarb'),(r'^Rhubarb$','rhubarb'),
 (r'^Spinach \(Normal','spinach'),(r'^Spinach \(Pak','pak_choi'),(r'^Spinach Italian','baby_spinach'),(r'^Spring Onion','spring_onion'),
 (r'^Sugar-Snap','sugar_snap'),(r'^Sukuma','sukuma'),(r'^Sweet Corn','sweet_corn'),(r'^Tomato \(Cherry','tomato_cherry'),
 (r'^Tomato \(English','tomato_round'),(r'^Tomato \(Italian','tomato_italian'),
 (r'^Apples \(Green','apple_green'),(r'^Apples \(Red','apple_red'),(r'^Bananas \(Plantain','plantain'),(r'^Bananas Green','matoke'),
 (r'^Bananas','bananas'),(r'^Blueberries','blueberries'),(r'^Coconuts','coconut'),(r'^Grape Fruit','grapefruit'),(r'^Grapes','grapes'),
 (r'^Kiwi','kiwi'),(r'^Lemons','lemons'),(r'^Limes','limes'),(r'^Madafu$','madafu'),(r'^Mangoes','mango'),(r'^Melon \(Sweet','melon_sweet'),
 (r'^Melon \(Thorn','melon_thorn'),(r'^Melon \(Water','watermelon'),(r'^Oranges \(Pixie','pixie'),(r'^Oranges','oranges'),
 (r'^Passion Fruit \(Black','passion_black'),(r'^Passion Fruit \(Yellow','passion_yellow'),(r'^Paw Paw \(Mountain','pawpaw_mountain'),
 (r'^Paw Paw','pawpaw'),(r'^Pears','pears'),(r'^Pineapple$','pineapple'),(r'^Pomegranates','pomegranate'),(r'^Raspberries','raspberries'),
 (r'^Strawberries \(Frozen','strawberries_frozen'),(r'^Strawberries \(Fresh','strawberries'),(r'^Tangerines','tangerines'),(r'^Tree Tomatoes','tree_tomato'),
 (r'^Basil','basil'),(r'^Chives \(Flat','chives_flat'),(r'^Chives','chives'),(r'^Coriander','coriander'),(r'^Edible Flowers','edible_flowers'),
 (r'^Fennel','fennel'),(r'^Garlic','garlic'),(r'^Ginger','ginger'),(r'^Lemon Grass','lemon_grass'),(r'^Lemon Verbena','lemon_verbena'),
 (r'^Marjoram','marjoram'),(r'^Mint \(Apple','apple_mint'),(r'^Mint','mint'),(r'^Oregano','oregano'),(r'^Parsley \(Curly','parsley_curly'),
 (r'^Parsley Curly','parsley_curly'),(r'^Parsley Flat','parsley_flat'),(r'^Rocket','rocket'),(r'^Rosemary','rosemary'),(r'^Sage','sage'),
 (r'^Tarragon','tarragon'),(r'^Thyme','thyme'),(r'^Turmeric','turmeric'),(r'^Watercress','watercress'),(r'^Sorrel','sorrel'),
 (r'^Artichokes','artichoke'),(r'^Gooseberry','gooseberry'),(r'^Herbs \(Mixed','herb_box'),(r'^Strawberry Plants','strawberry_plant'),(r'^Strawberry splits','strawberry_runner'),
 (r'^Bocconcini','bocconcini'),(r'^Brie','brie'),(r'^Camembert','camembert'),(r'^Cheddar','cheddar'),(r'^Cottage','cottage_cheese'),
 (r'^Cream Cheese','cream_cheese'),(r'^Cream','cream'),(r'^Dip \(Smoked','baba_ganoush'),(r'^Dip \(whipped','feta_dip'),(r'^Eggs','eggs'),
 (r'^Feta','feta'),(r'^Gouda','gouda'),(r'^Greek Yogurt','greek_yogurt'),(r'^Halloumi','halloumi'),(r'^Hummus','hummus'),(r'^Mascarpone','mascarpone'),
 (r'^Milk','milk'),(r'^Mozzarella','mozzarella'),(r'^Paneer','paneer'),(r'^Ricotta','ricotta'),(r'^Sour Cream','sour_cream'),
 (r'^String','string_cheese'),(r'^Bleu de Brun','blue_cheese'),(r'^Vanilla Bean','ice_vanilla'),(r'^Chocolate Ice','ice_chocolate'),
 (r'^Chocolate Chip Fudge','ice_chocolate'),(r'^Caramel','ice_caramel'),(r'^Cookies And Cream','ice_cookies'),
 (r'^Beef Boerwors','boerwors'),(r'^Beef Striploin','striploin'),(r'^Chicken \(Whole','chicken_whole'),(r'^Chicken Breast','chicken_breast'),
 (r'^Chicken Liver','chicken_liver'),(r'^Chicken Thigh','chicken_thigh'),(r'^Droewors','droewors'),(r'^Duck \(Whole','duck_whole'),
 (r'^Duck Breast','duck_breast'),(r'^Duck Legs','duck_legs'),(r'^Fish Fillet','snapper'),(r'^Ham','ham'),(r'^Minced Beef','minced_beef'),
 (r'^Pork Belly','pork_ribs'),(r'^Pork Loin','pork_chops'),(r'^Prawns','prawns'),(r'^Premium Pork Sausages','pork_sausages'),
 (r'^Salmon Burgers','salmon_burger'),(r'^Salmon Portion','salmon_portion'),(r'^Smoked Salmon','smoked_salmon'),(r'^Squid','squid'),(r'^Streaky Bacon','bacon'),
 (r'^Apple Juice','apple_juice'),(r'^Beetroot Juice','beetroot_juice'),(r'^Madafu In a Bottle','madafu_bottle'),(r'^Mango Juice','mango_juice'),
 (r'^Orange Juice','orange_juice'),(r'^Passion Juice','passion_juice'),(r'^Pineapple Juice','pineapple_juice'),(r'^Pineapple Mint Juice','pineapple_juice'),
 (r'^Tree Tomato Juice','tree_tomato_juice'),(r'^Kombucha','kombucha'),(r'^Water \(20','water_big'),(r'^Water \(Sparkling','water_sparkling'),(r'^Water','water_still'),
 (r'^Chutney','chutney'),(r'^Harissa','harissa'),(r'^Honey','honey'),(r'^Jam','jam'),(r'^Marmalade','marmalade'),(r'^Tea Leaves','tea'),(r'^Bouquet','bouquet'),
]
